### ISSUE TITLE
Support Fastify 5

### ISSUE THREAD

**Issue by stefano-8wave** [L2jLiga/fastify-decorators#1034]
Fastify 5 support needed.
Alternatively Fastify has a built-in decorators usage like this plugin?

**Comment by L2jLiga** [comment]
v3 already support fastify 5
https://github.com/L2jLiga/fastify-decorators/releases/tag/v3.16.0

**Comment by stefano-8wave** [comment]
> v3 already support fastify 5 https://github.com/L2jLiga/fastify-decorators/releases/tag/v3.16.0

I've got this runtime error with that version:
FastifyError [Error]: fastify-plugin: fastifyDecorators - expected '^3.0.0 || ^4.0.0' fastify version, '5.0.0' is installed

**Comment by L2jLiga** [comment]
Well, this makes sense, forgot to adjust constraint..
fixed in v3.16.1
