### ISSUE TITLE
Body schema validation

### ISSUE THREAD

**Issue by camisetags** [L2jLiga/fastify-decorators#105]
Hi!

Thanks for the amazing project, it's helping me a lot!

I'm having an issue on controllers when I try to insert schema validation, like this:
```ts
@POST('/', { schema })
  public async create(
    request: FastifyRequest<{ Body: CreateTransactionSchema }>,
    response: FastifyReply,
  ): Promise<FastifyReply> {
...
```
And I have a schema like this:
```ts
export const schema = {
  schema: {
    body: {
      type: 'object',
      requiredKeys: ['title', 'value', 'category', 'realized_date'],
      properties: {
        title: { type: 'string' },
        value: { type: 'number' },
        category: { type: 'string' },
        realized_date: { type: 'string' },
      },
    },
  },
};
```
When I try to run this method on postman, for example, it simply bypass my schema validation. 
Do you have any suggestion what I have to do to handle schema validation on the `body` of requests?

**Comment by L2jLiga** [comment]
Hi there!

Which version you use? There was a fix in v3.2.1  for bug which makes `@POST`/`@GET` etc decorators to ignore second argument.

I see an error in your schema as well, just extract `schema` value from `schema` variable:

```typescript
export const schema: FastifySchema = {
  body: {
    type: 'object',
    requiredKeys: ['title', 'value', 'category', 'realized_date'],
    properties: {
      title: { type: 'string' },
      value: { type: 'number' },
      category: { type: 'string' },
      realized_date: { type: 'string' },
    },
  },
};
```

**Comment by camisetags** [comment]
Hi, thanks for the reply.

I'm using version 3.6.0 of fastify-decorators and version 3.9.1 of fastify.
Sorry for the mistake, I was using your schema code on my refactor with the same code on controller, but it still bypassing my schema validation.

**Comment by L2jLiga** [comment]
Can you provide examples of requests and what is in request.body?

**Comment by L2jLiga** [comment]
Just remember that according to Fastify [Validation and Serialization](https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#validator-compiler) docs `Ajv` by default will try to [coerce](https://github.com/epoberezkin/ajv#coercing-data-types) the values to the types specified in schema `type` keywords, both to pass the validation and to use the correctly typed data afterwards. It also will remove additional properties in payload.

so probably your issue may be fixed by disabling coerce in fastify options:

```typescript
const app= fastify({
  ajv: {
    removeAdditional: true,
    useDefaults: true,
    coerceTypes: false, // Here's the change to Fastify's default options
    nullable: true,
  }
})
```

**Comment by unematiii** [comment]
Shouldn't it be `required` instead of `requiredKeys`? [See docs](https://ajv.js.org/keywords.html#required)

**Comment by L2jLiga** [comment]
Good catch! It defenitely should be `requried`, thanks!

**Comment by camisetags** [comment]
Thanks @L2jLiga and @unematiii!

Both changes worked for me. But following fastify's docs, the wright config for `avj` is:

```ts
const app = fastify({
    ajv: {
      customOptions: {
        removeAdditional: true,
        useDefaults: true,
        coerceTypes: false, // Here's the change to Fastify's default options
        nullable: true,
      },
    },
  });
```

With this on configs and `required` set on schema, ererything worked perfectly for me. 😄 
Thanks again!

**Comment by L2jLiga** [comment]
Solved😎
