### ISSUE TITLE
Upgrading to 3.7.0

### ISSUE THREAD

**Issue by unematiii** [L2jLiga/fastify-decorators#113]
I'm having a bit of trouble upgrading to latest (after esm/cjs changes), some of my tests (ts-jest) now fail with:

```
 /Users/mati/xxx/node_modules/fastify-decorators/testing/index.js:8
    export { configureControllerTest, } from './configure-controller-test.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { configureServiceTest } from 'fastify-decorators/testing';
```

Linting tests also fails:

```
/Users/mati/xxx/tests/unit/yyyy/services/zzz.service.spec.ts
  1:1   error    Resolve error: Cannot find module '/Users/mati/xxx/node_modules/fastify-decorators/testing/index.cjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:907:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:900:15)
    at resolveExports (internal/modules/cjs/loader.js:432:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at findModulePath (/Users/mati/xxx/node_modules/eslint-import-resolver-alias/index.js:99:27)
    at Object.exports.resolve (/Users/mati/xxx/node_modules/eslint-import-resolver-alias/index.js:75:10)
    at v2 (/Users/mati/xxx/node_modules/eslint-module-utils/resolve.js:117:23)
    at withResolver (/Users/mati/xxx/node_modules/eslint-module-utils/resolve.js:122:16)
    at fullResolve (/Users/mati/xxx/node_modules/eslint-module-utils/resolve.js:139:22)
    at relative (/Users/mati/xxx/node_modules/eslint-module-utils/resolve.js:84:10)  import/namespace
```

I'm not entirely sure what needs to be changed here... Any help will be appreciated.

---

Update:

Might not be related, but in package.json I can see 
```
    "./testing": {
      "import": "./testing/index.js",
      "require": "./testing/index.cjs"
    }
```
however, there is no `index.cjs` present...

**Comment by L2jLiga** [comment]
My bad, forgot to add `fastify-decorators/testing` to rollup config, published v3.7.1

**Comment by unematiii** [comment]
Thanks! That removed the linting errors, but my tests still fail.

**Comment by unematiii** [comment]
Okay managed to get rid of `SyntaxError: Unexpected token 'export'` error with custom ts-config (`"allowJs": true, "module": "ESNext"`) and using `transform` and `transformIgnorePatterns` in jest config. Hovever, now all async service tests fail with:

```
TypeError: Cannot read property 'then' of undefined

      44 |   describe('initializer', () => {
      45 |     it('initializes db client and attaches logger functions for knex `query-response` and `query-error` events', async () => {
    > 46 |       const service = await configureServiceTest({
         |                             ^
      47 |         service: DatabaseService,
      48 |       });
```

**Comment by unematiii** [comment]
Looks like in `node_modules/fastify-decorators/testing/configure-service-test.js`, at following lines
```js
if (promise == null)
                    promise = hasAsyncInitializer(service) ? readyMap.get(service).then(() => target) : Promise.resolve(target);
```
`hasAsyncInitializer` returns `true` but next call to `readyMap.get(service)` evaluates to `undefined` which results in error...

**Comment by L2jLiga** [comment]
Are you building ESM?

**Comment by L2jLiga** [comment]
I weren't able to make work ESM+TS+Jest so in one of my projects I switched to tap and mocha in [ESM example](https://github.com/L2jLiga/fastify-decorators/tree/v3/examples/esm)

**Comment by L2jLiga** [comment]
Hope in Jest 27 it will work

**Comment by unematiii** [comment]
I am building for commonjs and everything works, except for tests.  So I created a separate tsconfig for tests:
```
"compilerOptions": {
    "lib": [
        "es2019",
        "es2020.promise",
        "es2020.bigint",
        "es2020.string"
    ],
    "module": "esnext",
    "target": "es2019",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": "./",
    "paths": {
        "@/*": [
            "src/*"
        ]
    },
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "allowJs": true,
    "moduleResolution": "node"
},
```

Now I just realized, that while `configureServiceTest` is loaded from ESM module ('.js'), service `INITIALIZER` and `CREATOR` are assigned in `decorators/service.cjs` and `decorators/initializer.cjs` respectively, hence, **different instance of `readyMap` is used** - I have no idea why....

Following apporach doesn't seem to work either:

jest.config.ts:
```ts
preset: 'ts-jest/presets/js-with-ts',
transform: {
  '^.+\\.(j|t)s?$': 'ts-jest',
},
transformIgnorePatterns: ['<rootDir>/node_modules/(?!fastify-decorators)'],
```

tsconfig.spec.json:
```json
{
  "compilerOptions": {
        "lib": [
            "es2019",
            "es2020.promise",
            "es2020.bigint",
            "es2020.string"
        ],
        "module": "commonjs",
        "target": "es2019",
        "strict": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "baseUrl": "./",
        "paths": {
            "@/*": [
                "src/*"
            ]
        },
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "strictNullChecks": true,
        "allowJs": true
    }
}
```

**Comment by unematiii** [comment]
> I weren't able to make work ESM+TS+Jest so in one of my projects I switched to tap and mocha in [ESM example](https://github.com/L2jLiga/fastify-decorators/tree/v3/examples/esm)

Can you explain further what are the obstacles here?

**Comment by L2jLiga** [comment]
I'm going to create and investigate sample repository tomorrow, for a moment you can try to build your application and tests and then run tests on transpiled code or switch to another test framework (I think you would like avoid it)

**Comment by unematiii** [comment]
I guess the CJS import happens because ts-jest transforms `fastify-decorators/testing/configure-service-test.js` to CJS and from there on `require`-s kick in...

**Comment by unematiii** [comment]
> I'm going to create and investigate sample repository tomorrow, for a moment you can try to build your application and tests and then run tests on transpiled code or switch to another test framework (I think you would like avoid it)

Thanks! Actually building tests and testing against dist might make sence. I can't afford to switch to another testing FW atm...

**Comment by unematiii** [comment]
Update: I ended up reverting all the changes and kept my original ts-config (module: 'commonjs') by simply hard-mapping js to cjs in `jest.config.ts`:
```js
moduleNameMapper: {
  // ...
  'fastify-decorators/testing': 'fastify-decorators/testing/index.cjs',
  // ...
},
```

**Comment by L2jLiga** [comment]
Very nice! I think this should be noticed [here](https://github.com/L2jLiga/fastify-decorators/blob/v3/docs/Testing.md)

**Comment by L2jLiga** [comment]
Here's PR about adding support for TS + ESM: https://github.com/facebook/jest/pull/10823, it's already merged but I didn't managed how to make it work yet, for a while I added section to documentation about [configuring Jest](https://github.com/L2jLiga/fastify-decorators/blob/v3/docs/Testing.md#jest--26)

**Comment by unematiii** [comment]
Thanks, will check this soon.

**Comment by unematiii** [comment]
I think this can be closed now
