### ISSUE TITLE
Any way to disable dependency injection?

### ISSUE THREAD

**Issue by normano** [L2jLiga/fastify-decorators#14]
It's no big deal as I can stay on version 1.3.0 and will maintain my own fork starting at that version, but I use another dependency injector library with the controllers and version 2 introduces dependency injection which conflicts with my current one. I can't get controllers to load up without hitting parameter needs @Serivce annotation error.

**Comment by L2jLiga** [comment]
There is no such option atm

**Comment by L2jLiga** [comment]
Can you provide an example of conflict code?

**Comment by normano** [comment]
No big deal, don't worry about it.
