### ISSUE TITLE
OpenAPI Doc Generation

### ISSUE THREAD

**Issue by dlydiard** [L2jLiga/fastify-decorators#23]
Are there any plans or suggestions on making this project able to generate OpenApi 3 specs?

such as https://github.com/lukeautry/tsoa
or https://www.npmjs.com/package/typescript-rest-swagger

it would seem redundant to use decorators with the same name and mixing decorators together from these projects.

**Comment by L2jLiga** [comment]
Hi there!

There are no such plans at the moment but I would suggest:
- try [@sinclair/typebox](https://www.npmjs.com/package/@sinclair/typebox) to generate JSON Schema and TypeScript types
- try [fastify-swagger](https://www.npmjs.com/package/fastify-swagger) for OpenApi 2 specs
- or try [fastify-oas](https://www.npmjs.com/package/fastify-oas) for OpenApi 3 specs

```typescript
import { Type, Static } from '@sinclair/typebox'
import { Controller, GET } from 'fastify-decorators';

const body = Type.Object({
    email:    Type.String({ format: 'email' }), 
    address:  Type.String(),
    quantity: Type.Number({ minimum: 1, maximum: 99 }),
    option:   Type.Union([
        Type.Literal('pizza'), 
        Type.Literal('salad'),
        Type.Literal('pie')
    ])
})

@Controller()
class Ctrl {
  @GET('/test', { schema: { body } })
  get({ body }: FastifyRequest<{ Body: Static<typeof body> }>) {
    // using body props here
  }
}

```

**Comment by L2jLiga** [comment]
Here's one more example for TypeBox:
https://github.com/fastify/fastify/issues/1668#issuecomment-594998612

**Comment by dlydiard** [comment]
thanks, the example you gave is promising!
