### ISSUE TITLE
Get request from services

### ISSUE THREAD

**Issue by metecsis** [L2jLiga/fastify-decorators#387]
I have an app with controllers as `ControllerType.REQUEST`, i'm in need of look up something from the request object.

Is there a way to access request object inside an injected service from controller?

**Comment by L2jLiga** [comment]
I think there's currently no way to do that, PR is welcomed ☺️ 
Otherwise I can take a look on what I can do later this week or next week

**Comment by JesusFregoso** [comment]
im struggling with the same feature.

**Comment by L2jLiga** [comment]
I've started working on this feature, PR already in place #555

**Comment by L2jLiga** [comment]
Released as [v4.0.0-next.1](https://github.com/L2jLiga/fastify-decorators/releases/tag/v4.0.0-next.1)

For upgrade guide see [Migration to v4](https://github.com/L2jLiga/fastify-decorators/blob/v4/docs/Migration%20to%20v4.md) guide

- [`fastify-decorators`](https://www.npmjs.com/package/fastify-decorators/v/4.0.0-next.0)
- [`@fastify-decorators/simple-di`](https://www.npmjs.com/package/@fastify-decorators/simple-di)

**Comment by L2jLiga** [comment]
Released as [v3.14.0](https://github.com/L2jLiga/fastify-decorators/releases/tag/v3.14.0). 

Now feature available in both v3 & b4, closing.
