### ISSUE TITLE
Add support for Services that need a async setup

### ISSUE THREAD

**Issue by mihai1voicescu** [L2jLiga/fastify-decorators#48]
There are several examples where a Service needs a async step to be completely initialised.
For example database connections:

https://github.com/L2jLiga/fastify-decorators/blob/v3/examples/typeorm/src/services/connection.service.ts
https://github.com/L2jLiga/fastify-decorators/blob/v3/examples/typeorm/src/facades/message.facade.ts

A basic way to do this would be to look for a promise property named `ready` (or even better, a symbol to avoid collisions) on a service and await on them before starting the server.

A more advanced way, which can be done afterwards, would be a decorator on an async function but a Service may require other Services have inited so this is more tricky and require a big time investment.

The good news is the basic way does not conflict with the more advanced way so it can be built separately and be supported independently. Also the init dependency graph can be manually solved with the basic version by awaiting the other services to init.

What do you think? I would be happy to do a PR for the basic one, as I need it 😄

**Comment by L2jLiga** [comment]
Hi there,

I like the idea, can you provide an example on how would you use it? In my point of view it may look like:

```typescript
import { Service, Initializer } from 'fastify-decorators';

@Service()
export class MyService {
  constructor(private dependency: Dependency) {}

  @Initializer()
  async init(): Promise<void> {
    // some async-await stuff here
  }
}
```

**Comment by mihai1voicescu** [comment]
The thing is we have to take in account that services may depend on other services for their init, like this:

```ts
@Service()
export class MyService {
    @Inject(OtherAsyncService)
    private other!: OtherAsyncService;

    @Initializer()
    async init(): Promise<void> {
        // other is guaranteed to be initialised here by the framework
       await other.someAsync();
        // some async-await stuff here
    }
}
```

The problem gets even more complex as some services may require only some parts of their services to be inited and you can end up in a deadlock when circular dependencies come into play (never used a circular dependency in your framework so I don't know if you support them).

You can however move the async dependency resolution to the dev by requiring them to do something like this:

```ts
const READY = Symbol.for(`FastifyDecoratorsReadySym`)

@Service()
export class MyService {
    @Inject(OtherAsyncService)
    private other!: OtherAsyncService;

    @ Initializer([OtherAsyncService])
    async init(): Promise<void> {
        // other is guaranteed to be initialised here by the framework
       await other.someAsync();
        // some async-await stuff here
    }
}
```

This should offer a big degree of flexibility (because you decouple the constructer from the async init code, and you can do them in phases) and the user is free to select what he needs for his own async init. Also has the bonus of the nice decorator interface.

Approach 2 is rather simple to implement:
1. Wrap each Initializer call in a promise which awaits it's dependencies
2. Collect all of the wrapping promises in random order in an array
3. await Promise.all on them and it should resolve if no async circular deps were introduced

As a bonus it's easy to analyse them and tell if any async circular deps were found.

For the moment this is the best I could come up with but if I think of something better I will write to you.

What do you think?

**Comment by L2jLiga** [comment]
Sounds good to me.

Initializer signature will be:

```typescript
function Initializer(dependencies?: Array<Constructor<any>>): MethodDecorator;
```

----

1. When dependencies are omit -> wait for everything or don't wait at all?
1. When dependencies is `[]` -> wait for nothing
1. When dependencies are specified -> wait for every specified dependency

**Comment by L2jLiga** [comment]
Also I'm worried about [`configureServiceTest`](https://github.com/L2jLiga/fastify-decorators/blob/v3/lib/testing/configure-service-test.ts#L21-L27) how will it deal with initializers?

**Comment by L2jLiga** [comment]
And one more question - how it should inject dependencies into Controllers when they has initializers? Wait for initialization and then instantiate controller or how?

**Comment by mihai1voicescu** [comment]
The current functionality should not be affected at all. This is an extension to the existing behaviour.

The normal flow for injecting should be used (via the constructor).

On top of this if a `@Initializer` function is detected in the service:

1. If no dependencies were specified in the annotation `@Initializer` call the async function and collect the result.
2. If dependencies were specified in the annotation `@Initializer(Dep1, De2)` create a wrapper function which awaits them and calls the annotated initialiser and collect the result of this function.

Something like this
```js
const initializers = [];
for (const service of services) {
  if (service.initilizer) {
    if (!service.initilizer.deps) initializers.push(service.initilizer());
    else initializers.push((async () => {
        await Promise.all(service.initilizer.deps)
        await service.initilizer()
    }) () )
}

await Promise.all(initializers);
```

The annotated function should have no arguments and should be called **only after the all the services constructors** were called.

This way it's an opt in feature and should not require a major version increment.

**Comment by L2jLiga** [comment]
Thanks!
Are you going work on this feature?

**Comment by mihai1voicescu** [comment]
If it OK with you I would be glad to. But it will have to wait till the weekend I think 😄

**Comment by L2jLiga** [comment]
Sure, I'm ok 👍

**Comment by L2jLiga** [comment]
Hi @mihai1voicescu, weekends are here! How is your feeling on it?

**Comment by mihai1voicescu** [comment]
Had some problems during the weekend and didn't get to finish. Gona try and finish these days.

**Comment by mihai1voicescu** [comment]
Services are only singletons no?

**Comment by L2jLiga** [comment]
correct

**Comment by L2jLiga** [comment]
Hi @mihai1voicescu,
Any luck on this so far?

**Comment by mihai1voicescu** [comment]
Had some personal issues, sorry. It's almost done and I think I have time to work on it tomorrow. Sorry it took so long.
