### ISSUE TITLE
Class To JSON Schema Conversion

### ISSUE THREAD

**Issue by mekamleshk** [L2jLiga/fastify-decorators#565]
I am trying to convert my DTO class (Typescript) to JSON schema:

```javascript
import { IsNumber, IsString } from 'class-validator';
import { classToPlain } from 'class-transformer';

export class TodoDTO {
    @IsNumber()
    id?: number;

    @IsString()
    name?: string;

    @IsString()
    description?: string;
}

let todo = classToPlain(TodoDTO);

console.log('todo=>', todo);
```

I tried to use two packages class-transformer and class-validator to transform and validate TodoDTO class.

In console it gives output as todo=> [Function: TodoDTO]

Expected output:

```javascript
"TodoDTO": {
   "type": "object",
   "properties": {
       "id": { "type": "number" },
       "name": { "type": "string" },
       "description": { "type": "string" }
    },
   "required": [ "id", "name", "description" ]
}
```
I am trying to use TodoDTO class as a json-schema in fastify-typescript.

Any suggestions are welcome.

**Comment by L2jLiga** [comment]
Hi there!

There's pretty old issue in class-validator - https://github.com/typestack/class-validator/issues/5 and community plugin to c1onvert class-validator to JSON schemas - https://www.npmjs.com/package/class-validator-jsonschema

Does this help? 🙂

**Comment by mekamleshk** [comment]
Hi,

I tried this :

```javascript
import * as todoDtos from "./todo.dto";

import { validationMetadatasToSchemas } from 'class-validator-jsonschema'

export default todoDtos;

export const schemas = validationMetadatasToSchemas()
```

And in my App:

```javascript
import 'reflect-metadata'
import fastify from 'fastify'
import { bootstrap } from 'fastify-decorators';
import { resolve } from 'path';
import config from 'config';
import chalk from 'chalk';
import { dbConfig } from './interfaces/db.interface';
import { schemas } from './dtos';

const { env, host, port }: dbConfig = config.get('server');

const dash = chalk.bold.magenta;
const environment = chalk.bold.yellow;
const server = chalk.bold.cyan;
const swagger = chalk.bold.greenBright;

const app = fastify({ logger: { prettyPrint: false } });


(async () => {
    try {
        await app.register(require('fastify-swagger'), {
            routePrefix: '/explorer',
            openapi: {
                info: {
                    title: 'Fastify Typescript',
                    description: 'Testing the Fastify swagger API',
                    version: '3.0.0',
                    contact: {
                        email: "mekamleshk@gmail.com"
                    }
                },
                servers: [{ url: `http://${host}:${port}`, description: "Localhost (uses test data)" }],
                host: host,
                schemes: ['http'],
                consumes: ['application/json'],
                produces: ['application/json'],
                components: {
                    schemas,
                    securitySchemes: {
                        bearerAuth: {
                            type: 'http',
                            in: 'header',
                            scheme: 'bearer',
                            bearerFormat: 'JWT',
                        },
                    },
                },
            },
            uiConfig: {
                docExpansion: 'full',
                deepLinking: false
            },
            hideUntagged: true,
            exposeRoute: true
        });


        await app.register(bootstrap, {
            directory: resolve(__dirname, `controllers`),
            mask: /\.controller\./,
        });

        app.listen(port, host, (error, address) => {

            if (error) {
                app.log.error(error);
                process.exit(1)
            } else {
                console.info(dash(`= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =`));
                console.info(environment(` 🌿 Running environment: ${env?.toUpperCase()}`));
                console.info(server(` 🚀 App listening on: ${address} ✅`));
                env === 'development' && console.info(swagger(` 📚 Swagger is running on: ${address}/explorer`));
                console.info(dash(`===============================================================`));
            }

        })
    } catch (error) {
        app.log.error(error);
        process.exit(1)
    }
})();
```

I got the DTO converted to schema like this :

![image](https://user-images.githubusercontent.com/16983847/140897884-8d909a6c-7c25-4fe7-a6ac-b5d3f0731dcb.png)

And i tried to use it in todo controller this way:

```javascript
import { FastifyReply, FastifyRequest, FastifySchema, } from 'fastify';
import { Controller, GET, POST } from 'fastify-decorators';
import { TodoService } from '../services/todos.service';
import { TodoCountFilterDTO } from '../dtos/todo.dto';


@Controller({ route: '/todos' })
export default class TodoController {

    constructor(private _todoService: TodoService) { }

    @GET({
        url: '/count',
        options: {
            schema: {
                tags: ['Todos'],
                description: 'Returns count of todos',
                querystring: { "$ref": "#/components/schemas/TodoCountFilterDTO" },
                response: { 200: {}, 401: { description: 'Unauthorized Access', type: 'object' }, 400: {}, 404: {}, 500: {} },
            } as FastifySchema
        }
    })
    async getTodosCount(req: FastifyRequest<{ Querystring: TodoCountFilterDTO }>, res: FastifyReply) {
        try {

            const filterBy: TodoCountFilterDTO = req.query;

            return { count: await this._todoService.getTodosCount(filterBy) };

        } catch (error: any) {
            return res.status(500).send({
                error: {
                    statusCode: 500,
                    description: error.message,
                    name: 'Server Error',
                    code: 'SOMETHING_WENT_WRONG',
                },
            });
        }
    }
```


But it throws this error:

> {"level":50,"time":1636449686809,"pid":22204,"hostname":"kamlesh","name":"FastifyError","code":"FST_ERR_SCH_VALIDATION_BUILD","message":"Failed building the validation schema for GET: /todos/count, due to error can't resolve reference #/components/schemas/TodoCountFilterDTO from id #","statusCode":500,"stack":"FastifyError: Failed building the validation schema for GET: /todos/count, due to error can't resolve reference #/components/schemas/TodoCountFilterDTO from id #\n    at Boot.<anonymous> (D:\\projects\\fastify-typescript\\node_modules\\fastify\\lib\\route.js:309:19)\n    at Object.onceWrapper (node:events:509:28)\n    at Boot.emit (node:events:402:35)\n    at D:\\projects\\fastify-typescript\\node_modules\\avvio\\boot.js:153:12\n    at D:\\projects\\fastify-typescript\\node_modules\\avvio\\plugin.js:270:7\n    at done (D:\\projects\\fastify-typescript\\node_modules\\avvio\\plugin.js:202:5)\n    at check (D:\\projects\\fastify-typescript\\node_modules\\avvio\\plugin.js:226:9)\n    at node:internal/process/task_queues:141:7\n    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)\n    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)","type":"Error","msg":"Failed building the validation schema for GET: /todos/count, due to error can't resolve reference #/components/schemas/TodoCountFilterDTO from id #"}


i want to load the schema in something like this:

![image](https://user-images.githubusercontent.com/16983847/140898594-65af631a-93f5-4626-9acc-987b1d75ed68.png)

**Comment by L2jLiga** [comment]
This happens because you have to add this schemas to fastify by using [`addSchema`](https://www.fastify.io/docs/latest/Server/#addschema), it could be something like this:

```typescript
for (const [name, schema] of schemas) {
  app.addSchema({ ...schema, $id: `#/components/schemas/${name}` }
}
```

**Comment by mekamleshk** [comment]
@L2jLiga 

Do i need to convert the data type, i see it is an object but still can't loop over it

![image](https://user-images.githubusercontent.com/16983847/140903416-67693d7b-dfc2-4ce7-a501-2e80cc30b2ed.png)

**Comment by L2jLiga** [comment]
Sure, my bad, missed `Object.entries`

**Comment by mekamleshk** [comment]
Hi,

Now ids (definition ids) are dynamic but still can't use it

![image](https://user-images.githubusercontent.com/16983847/140909712-db8b3e0a-c704-4f9d-ab23-3fb157aabba0.png)


![image](https://user-images.githubusercontent.com/16983847/140910199-2f9379a3-3de4-472c-8663-1589add1e8b8.png)


![image](https://user-images.githubusercontent.com/16983847/140910251-ba7206d0-f57f-4a4a-9454-b06edfcedd70.png)

![image](https://user-images.githubusercontent.com/16983847/140910343-a0b3ddf2-3d02-4d19-bc58-c211c1fb93b6.png)


In swagger it shows like params:

![image](https://user-images.githubusercontent.com/16983847/140910497-3c932dcb-0cf5-40ba-9fc7-bd0e52d81853.png)


I want to  it to be like querystring:

![image](https://user-images.githubusercontent.com/16983847/140910654-63f96829-b1ad-4d72-b0a4-1cfda8383b02.png)

**Comment by mekamleshk** [comment]
@L2jLiga 

Okay, i think i got it now it worked like this:

```javascript
    @GET({
        url: '/count',
        options: {
            schema: {
                tags: ['Todos'],
                description: 'Returns count of todos',
                querystring: { $ref: 'TodoCountFilterDTO#' },
                response: { 200: TodosCountSchema, 401: { description: 'Unauthorized Access', type: 'object' }, 400: {}, 404: {}, 500: {} },
            } as FastifySchema
        }
    })
```

Thank you so much 👍🏻
