### ISSUE TITLE
Unusual Syntax

### ISSUE THREAD

**Issue by MetalMichael** [L2jLiga/fastify-decorators#6]
Hi there. I like the idea of the project, and it definitely looks useful.

I wonder though why you've chosen a fairly unusual object syntax for decorators, that looks a little over-complicated in the implementation files.

Rather than `@Get({ uri: '/something'  });`
Why not `@Get('/something')`?

This could even be backwards compatible, or support more complex overloading with the use of Typescript's union types.

The signature for Get could be `args : RouteConfig | string`, allowing for complex configuration when needed, and also simplicity to suit other situations more succinctly.

Much like https://www.npmjs.com/package/typescript-rest - or similar to ASP.Net, or Spring, or other examples, more complex data could and maybe would be clearer added through additional decorators rather than more complex ones.

**Comment by L2jLiga** [comment]
Hi @MetalMichael,
Actually good point! Will take a look what can I do, also I work on next major release time-to-time, hopefully some day I will release it :)

**Comment by L2jLiga** [comment]
I have implemented your proposal under `next` branch in https://github.com/L2jLiga/fastify-decorators/commit/fd46f63d3f31fc93fd00de477713620a0b395bf6 commit

**Comment by L2jLiga** [comment]
Hi there!
It would be great if you have time to check documentation for upcomming v2 and leave feedback :)

**Comment by L2jLiga** [comment]
Released [v2.0.0-0](https://github.com/L2jLiga/fastify-decorators/releases/tag/v2.0.0-0) under `next` tag
