### ISSUE TITLE
Problem with extending AbstractController

### ISSUE THREAD

**Issue by LucasBoberg** [L2jLiga/fastify-decorators#7]
Hi!

When I extend my controller with AbstractController it says:
`Class constructor AbstractController cannot be invoked without 'new'`

Here is my complete controller:
```
@Controller({ route: "/api/addresses" })
export default class AddressesController extends AbstractController {
  @GET({ url: "/" })
  async getAddresses(request: FastifyRequest<IncomingMessage>, reply: FastifyReply<ServerResponse>) {
    try {
      const addressRepository = await getManager().getCustomRepository(AddressRepository);
      const addresses = await addressRepository.find();
      return addresses;
    } catch (error) {
      throw boom.boomify(error);
    }
  }
}
```

**Comment by LucasBoberg** [comment]
Solved it!

I just had to change my typescript target to es6 from es5 in tsconfig.json from:
`"target": "es5"`
to
`"target": "es6"`

**Comment by L2jLiga** [comment]
Hi there!
It's very nice that you've solved your issue! Why you use es5 target? fastify-decorators use es2017 target as far as minimal node.js engine is 8 and it supports all es2017 features.

**Comment by LucasBoberg** [comment]
Hi!
I didn't give it much thought at first since it is my first time using typescript, so no other reason.
