### ISSUE TITLE
Any ways to apply `onRequest ` or `preHandler ` in @controller?

### ISSUE THREAD

**Issue by iketiunn** [L2jLiga/fastify-decorators#761]
I was going to implement auth guards with https://github.com/fastify/fastify-jwt#usage.
Does it possible to apply the `onRequest ` or `preHandler` in controller to prevent duplications?

Or how do you guys handle authtications using this fantastic library 🧐?

**Comment by L2jLiga** [comment]
Hi @iketiunn =)

Did you try to make it via `@Hook` decorator?

Take a look on example:
https://github.com/L2jLiga/fastify-decorators/blob/53da6ad271caaea7a697d2ca814ce6dceecda16e/examples/controllers/src/hooks/stateful.controller.ts#L14-L17

**Comment by iketiunn** [comment]
> Hi @iketiunn =)
> 
> Did you try to make it via `@Hook` decorator?
> 
> Take a look on example:
> https://github.com/L2jLiga/fastify-decorators/blob/53da6ad271caaea7a697d2ca814ce6dceecda16e/examples/controllers/src/hooks/stateful.controller.ts#L14-L17

Yes, that works perfecty with controller  inheritance. Now I can have a feature like Auth Guard to implement in my application.

Many thanks😍.

**Comment by L2jLiga** [comment]
You're welcome =)
