### ISSUE TITLE
Problems with preValidation

### ISSUE THREAD

**Issue by LucasBoberg** [L2jLiga/fastify-decorators#8]
Hello!

I cannot get the preValidation to work using my own fastify plugin.
`preValidation: [this.instance.authenticate]`
only returns "Cannot read property of undefined" and I am extending AbstractController in my controller and I can log this.instance.

I want it to only run on some routes and not all. Am I doing something wrong?

**Comment by L2jLiga** [comment]
Hi-hi!

Very interesting use case, actually idk why this happens and gonna investigate. Currently I'm working on v2 with dependency injection mechanism which also should be able to solve your issue btw :)

**Comment by L2jLiga** [comment]
This issue will be solved in v2, you can check this section of documentation: https://github.com/L2jLiga/fastify-decorators/blob/next/lib/docs/Controllers.md#accessing-fastifyinstance-in-decorators

Also it would be good if you can check the whole documentation of upcomming v2 and leave feedback about it :)

**Comment by LucasBoberg** [comment]
Hi!
Thanks for the new update, I am very excited!

Am I able to use v2 now and try it out early?

The docs for Controllers are a bit weird in the beginning mentioning handlers and then showing code for using controllers. Otherwise, I think it looks good.

**Comment by L2jLiga** [comment]
Thank you for feedback! I'm going to release in npm under the `next` tag tomorrow

**Comment by L2jLiga** [comment]
Released [v2.0.0-0](https://github.com/L2jLiga/fastify-decorators/releases/tag/v2.0.0-0) under `next` tag

**Comment by LucasBoberg** [comment]
Awesome! I will try it out right away!
