### ISSUE TITLE
Is there a way I can add a middleware to my routes specifically?

### ISSUE THREAD

**Issue by Squecy-R** [L2jLiga/fastify-decorators#832]
I've searched about it in the documentation but couldn't find anything. Some document files are missing. 
I've seen @Hook's example but I'm having trouble understanding it due to my insufficient experience.
Thanks for your help.

**Comment by L2jLiga** [comment]
Hi there, which kind of middleware you want to add?

**Comment by L2jLiga** [comment]
Hooks are suitable for handling requests at different stages, and `@Hook` is created to use this fastify hooks https://github.com/fastify/fastify/blob/3.x/docs/Reference/Hooks.md

I have to update docs a bit, to fix broken links since Fastify docs structure is changed

**Comment by Squecy-R** [comment]
I want to add a middleware to validate JWT. Thank you for answering my question.

**Comment by unematiii** [comment]
@Squecy-R Any hook from [this](https://www.fastify.io/docs/latest/Reference/Hooks/#prehandler) list?

**Comment by L2jLiga** [comment]
Well, `preHandler` is great place to check JWT token
Then it depends on where you need to check it?
In case if for all routes, then I would consider adding global preHandler hook in index.ts or smth like this.
 In case when this validation needed within specific controller then it would be better to use `@Hook` decorator:
```
@Hook('preHandler')
async validateJwt(request: FastifyRequest) {
  // ...
}
```

**Comment by L2jLiga** [comment]
Assume as fixed
