### ISSUE TITLE
QueryFailedError: ER_TABLE_EXISTS_ERROR

### ISSUE THREAD

**Issue by mekamleshk** [L2jLiga/fastify-decorators#847]
Hi, @L2jLiga 

Not sure why it is creating the table multiple times, below is my code repo with error:

[https://github.com/kamleshkatpara/fastify-demo](https://github.com/kamleshkatpara/fastify-demo)

![image](https://user-images.githubusercontent.com/16983847/202850958-ceceea3b-1cc6-4995-b92e-5f8441564e9c.png)

**Comment by L2jLiga** [comment]
Hey, I think you've faced with issue #834

**Comment by mekamleshk** [comment]
@L2jLiga when will it be released ?

**Comment by L2jLiga** [comment]
Once @unematiii and @akbarsahata confirm that all issues are gone for them, you can as well test latest version attached locally to confirm it solves your issue

**Comment by mekamleshk** [comment]
@L2jLiga  Yes, for me it works fine

**Comment by akbarsahata** [comment]
@L2jLiga seems to be working on me 👍🏻

**Comment by L2jLiga** [comment]
Published as [v3.15.0](https://github.com/L2jLiga/fastify-decorators/releases/tag/v3.15.0)
