### ISSUE TITLE
How to pass options to initializer?

### ISSUE THREAD

**Issue by rcronin** [L2jLiga/fastify-decorators#864]
Let's say I'm creating a Database Service that I want to inject into a controller...

I have some configuration properties/object that I want to inject into the Database Service. How could I accomplish this?

**Comment by L2jLiga** [comment]
Hey,

for that purpose I think you can use `injectablesHolder`:

```typescript
import { injectablesHolder } from 'fastify-decorators'
import { DatabaseOptionsToken } from './interfaces/database.js'

if (environment == 'prod') {
  injectablesHolder.injectSingleton(DatabaseOptionsToken, productionDatabaseOptionsObject)
}
```

and then use `@Inject` decorator to inject this options into Database Service:

```typescript

@Service()
export class DatabaseService {
  @Inject(DatabaseOptionsToken) declare connectionOptions: ConnectionOptions;

  @Initializer()
  async initialize() {
     connection.initialize(this.connectionOptions);
  }
}
```

**Comment by L2jLiga** [comment]
Please check [Dependency inversion](https://github.com/L2jLiga/fastify-decorators/blob/v3/docs/Services%20and%20dependency%20injection.md#dependency-inversion) section in docs and this issue: https://github.com/L2jLiga/fastify-decorators/issues/835

**Comment by rcronin** [comment]
@L2jLiga  - thanks for the response. I'm assuming based on this example, the token can just be a simple object instead of a class?

**Comment by L2jLiga** [comment]
Exactly
