### ISSUE TITLE
TypeError: classLoader is not a function when executing Jest Test

### ISSUE THREAD

**Issue by jgotty777** [L2jLiga/fastify-decorators#875]
Hi there. I tried to follow the example found [here](https://github.com/L2jLiga/fastify-decorators/tree/v4/plugins/simple-di#using-configurecontrollertest) to build a simple Jest test for my project. Running the test gives the following error message: 

![68c86f8c-5891-4a35-b14f-66db670545c7](https://user-images.githubusercontent.com/14024586/217622602-8c7af1da-f601-439d-abd4-7a8f14f5794c.jpg)

To be honest, I just started using fastify and decorators, so I honestly have no idea what information might be needed to assist. Attached are the controller file and the service file (note for the services my team decided to split the service into a service file and a repo file (holds only database logic), but I think both are just service objects). 

Repository
![image](https://user-images.githubusercontent.com/14024586/217623811-489ff167-6ad9-4860-a04b-82c223db69b1.png)

Service (uses Repository)
![image](https://user-images.githubusercontent.com/14024586/217624113-457bcc2d-b99c-4467-ac32-1e455e5ae382.png)

Controller
![image](https://user-images.githubusercontent.com/14024586/217624293-8581b480-442d-47ae-9d0f-61ec88f2458d.png)

Controller Test:
![image](https://user-images.githubusercontent.com/14024586/217624444-63a5dd58-097f-4598-ae2f-54ff2969f801.png)

If you need anything else I will do my best to provide it.

Thanks!

**Comment by JazielGuerrero** [comment]
I had the same issue of `TypeError: classLoader is not a function when executing Jest Test`. In my case I was using fastify-decoratos `v3.15.0` but the jest configuration I followed was for `v4`. After I updated to fastify-decoratos `v4.0.0-next.4` the test work and the error went away.

Test doc for v3.15.0 can be found [here](https://github.com/L2jLiga/fastify-decorators/blob/v3.15.0/docs/Testing.md)
Test doc for v4 can be found [here](https://github.com/L2jLiga/fastify-decorators/blob/v4/docs/Testing.md)

Hope this helps.
