### ISSUE TITLE
Service not being used with Initializer causing Timeouts

### ISSUE THREAD

**Issue by rcronin** [L2jLiga/fastify-decorators#877]
https://github.com/L2jLiga/fastify-decorators/blob/5f5aabca8fc059216791b187670050f83a84e210/plugins/simple-di/src/decorators/initializer.ts#L23

This needs to only attempt to initialize if any other service or controller depends on the service utilizing the initializer decorator. 

In our instance, we have created a shared service as part of a shared package. We cannot start our fastify instance unless we explicitly inject the service. We don't always need to inject this service. When we don't inject it, fastify will not start because the initializer gets called regardless and never resolves the promise.

**Comment by L2jLiga** [comment]
Hi there, can you check with 3.15.1 ? Or do you use v4?

**Comment by L2jLiga** [comment]
Assume as fixed
